version: '3'

services:
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
        - /opt/server/node_modules
        - ./:/opt/server
    environment:
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=local
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ../client
    environment: 
      - CHOKIDAR_USEPOLLING="true"
    volumes:
      - /opt/app/node_modules
      - ../client:/app
  nginx_dev:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx-dev
    ports:
      - "80:80"
    restart: "always"